### ISSUE TITLE
TypeError: Cannot call method 'match' of undefined

### ISSUE THREAD

**Issue by scottcorgan** [kenperkins/winston-papertrail#38]
Not sure where this error originates, but it pops up every so often. Any thoughts?

```
/var/app/current/node_modules/divshot-logger/node_modules/winston/lib/winston/config.js:26
  } else if (allColors[level].match(/\s/)) {
                              ^
TypeError: Cannot call method 'match' of undefined
    at Object.config.colorize (/var/app/current/node_modules/divshot-logger/node_modules/winston/lib/winston/config.js:26:31)
    at Papertrail.sendMessage (/var/app/current/node_modules/divshot-logger/node_modules/winston-papertrail/lib/winston-papertrail.js:347:68)
    at Papertrail.log (/var/app/current/node_modules/divshot-logger/node_modules/winston-papertrail/lib/winston-papertrail.js:299:10)
    at Transport.logException (/var/app/current/node_modules/divshot-logger/node_modules/winston/lib/winston/transports/transport.js:124:8)
    at logAndWait (/var/app/current/node_modules/divshot-logger/node_modules/winston/lib/winston/logger.js:631:15)
    at /var/app/current/node_modules/async/lib/async.js:125:13
    at Array.forEach (native)
    at _each (/var/app/current/node_modules/async/lib/async.js:46:24)
    at Object.async.each (/var/app/current/node_modules/async/lib/async.js:124:9)
    at Logger._uncaughtException (/var/app/current/node_modules/divshot-logger/node_modules/winston/lib/winston/logger.js:654:9)
```

**Comment by kenperkins** [comment]
What are your log levels? This seems to be coming from winston itself...

**Comment by scottcorgan** [comment]
I never set any log levels.

I thought that that may be the issue, but it doesn't happen all the time.

**Comment by kenperkins** [comment]
Hm. What version of winston got installed?

**Comment by scottcorgan** [comment]
`0.9.0`

**Comment by kenperkins** [comment]
Judging from https://github.com/winstonjs/winston/blob/v0.9.0/lib/winston/config.js#L26 it appears there's a case where `allColors[level]` can be null. This *looks* like a winston bug, but I'm not certain.

**Comment by scottcorgan** [comment]
That's a good point. I'm not too sure where to start, so I'll see about opening an issue on Winston.

**Comment by kenperkins** [comment]
Go ahead and leave this open/link it, and we'll wait and see.

**Comment by jahqueel** [comment]
This is fixed by #34

**Comment by Crispy1975** [comment]
We are still getting this issue in with the current latest versions of Winston and Winston PaperTrail: `"winston": "^2.1.0"`, `"winston-papertrail": "^1.0.1"`.

**Comment by jacobdr** [comment]
Ditto here

**Comment by Wadeck** [comment]
This seems to be due to the missing options "exceptionsLevel" that should go with "handleException".

You can look at winston\transport.js:134 => this.log(self.exceptionsLevel, [...]) and so the level is set to "undefined" in the winston\config.js generating the exception (inside the exception handler, inception?)

**Comment by cooloney** [comment]
I still hit this error.

```"winston": "2.2.0", "winston-papaertrail": "1.0.2"```

**Comment by troy** [comment]
@cooloney (and anyone else reading this): please switch to the current git commit in the `master` branch, which has #34 merged. https://github.com/kenperkins/winston-papertrail/pull/34#issuecomment-215891975 has more.

If no one reports issues in the next week or two, what's in `master` will become a new release.

**Comment by glenswift** [comment]
I'm getting this error even on `master` branch. It appears for me only when the error is not caught. Thus following workaround works fine for me:

```
process.on('uncaughtException', err => {
  instance.error(err); // instance is winston instance (with papertrail plugged in)
  setImmediate(process.exit);
});
```

**Comment by dmiddlecamp** [comment]
I double checked this today, PR #34 definitely fixes this issue, and I recommend we close this issue

**Comment by troy** [comment]
Confirmed resolved in #34. Closing.
